# Generated by Django 4.0.4 on 2022-05-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='Price',
            field=models.PositiveIntegerField(blank=True, default=-1, null=True),
        ),
    ]
