# Generated by Django 4.0.4 on 2022-05-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Density', models.FloatField()),
                ('CurrentStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrentStation', to='crowd_status.stationinfo')),
                ('TowardsStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TowardsStation', to='crowd_status.stationinfo')),
            ],
        ),
    ]
